"""
Django settings for the link shortener.

Originally generated by 'django-admin startproject' using Django 3.0.6,
upgraded to Django 5.2 LTS.

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# The project uses a flat layout: settings.py lives next to manage.py.
BASE_DIR = Path(__file__).resolve().parent


def env_flag(name, default="0"):
    return bool(int(os.environ.get(name, default)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "changeme")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_flag("DEBUG")

# A shortener answers on every domain it has a Domain object for, so the host
# check has to stay permissive. Narrow it via ALLOWED_HOSTS if you can.
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(";")


# Application definition

INSTALLED_APPS = [
    # django-unfold has to precede django.contrib.admin so that it can
    # override the admin templates.
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_api_key",
    "django_filters",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "shortener",
    "api",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wsgi.application"
ASGI_APPLICATION = "asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("POSTGRES_DB", BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("POSTGRES_USER", "user"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# The admin is the only UI there is, so send a bare login straight to it.
LOGIN_URL = "admin:login"
LOGIN_REDIRECT_URL = "admin:index"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

if DEBUG:
    AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.environ.get("TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "storage" / "static"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "storage" / "media"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_HOST = os.environ.get("SMTP_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("SMTP_PORT", "25"))

EMAIL_USE_TLS = env_flag("SMTP_TLS")
EMAIL_USE_SSL = env_flag("SMTP_SSL")

EMAIL_HOST_USER = os.environ.get("SMTP_USER", "user")
EMAIL_HOST_PASSWORD = os.environ.get("SMTP_PASSWORD", "pw")

DEFAULT_FROM_EMAIL = os.environ.get("FROM_EMAIL", "webmaster@localhost")

CSRF_TRUSTED_ORIGINS = os.environ.get(
    "CSRF_TRUSTED_ORIGINS",
    "http://127.0.0.1:8000",
).split(";")


# Security
# All off by default so a plain-HTTP deployment keeps working; turn them on in
# .env.prod once the service is behind TLS.
SESSION_COOKIE_SECURE = env_flag("SESSION_COOKIE_SECURE")
CSRF_COOKIE_SECURE = env_flag("CSRF_COOKIE_SECURE")
SECURE_SSL_REDIRECT = env_flag("SECURE_SSL_REDIRECT")
SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_flag("SECURE_HSTS_INCLUDE_SUBDOMAINS")

if env_flag("USE_X_FORWARDED_PROTO"):
    # Set this when a reverse proxy (nginx, traefik) terminates TLS.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Link shortener
# How long to wait when scraping a target URL for its open graph tags.
LINK_METADATA_TIMEOUT = float(os.environ.get("LINK_METADATA_TIMEOUT", "10"))


# Django REST framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "api.authentication.APIKeyAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Link shortener API",
    "DESCRIPTION": (
        "Create and manage short links, their open graph metadata and their "
        "view counts. Authenticate with `Authorization: Api-Key <key>`."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": "/api/v1",
    "COMPONENT_SPLIT_REQUEST": True,
    # Serve the Swagger/Redoc assets ourselves instead of from a CDN, so the
    # docs also work on a deployment without outbound internet access.
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}


# django-unfold
# https://unfoldadmin.com/docs/

UNFOLD = {
    "SITE_TITLE": _("Link shortener"),
    "SITE_HEADER": _("Link shortener"),
    "SITE_SUBHEADER": _("Short links with custom preview tags"),
    "SITE_SYMBOL": "link",
    "SITE_URL": None,
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": True,
    "COLORS": {
        "primary": {
            "50": "oklch(97.1% 0.014 254)",
            "100": "oklch(93.2% 0.032 255)",
            "200": "oklch(88.2% 0.059 254)",
            "300": "oklch(80.9% 0.105 252)",
            "400": "oklch(70.7% 0.165 254)",
            "500": "oklch(62.3% 0.214 259)",
            "600": "oklch(54.6% 0.245 262)",
            "700": "oklch(48.8% 0.243 264)",
            "800": "oklch(42.4% 0.199 265)",
            "900": "oklch(37.9% 0.146 265)",
            "950": "oklch(28.2% 0.091 267)",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Links"),
                "separator": False,
                "items": [
                    {
                        "title": _("Links"),
                        "icon": "link",
                        "link": reverse_lazy("admin:shortener_link_changelist"),
                    },
                    {
                        "title": _("Shares"),
                        "icon": "share",
                        "link": reverse_lazy("admin:shortener_share_changelist"),
                    },
                    {
                        "title": _("Domains"),
                        "icon": "public",
                        "link": reverse_lazy("admin:shortener_domain_changelist"),
                    },
                ],
            },
            {
                "title": _("Access"),
                "separator": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                    {
                        "title": _("API keys"),
                        "icon": "key",
                        "link": reverse_lazy("admin:api_userapikey_changelist"),
                    },
                ],
            },
            {
                "title": _("API"),
                "separator": True,
                "items": [
                    {
                        "title": _("Documentation"),
                        "icon": "api",
                        "link": reverse_lazy("api-docs"),
                    },
                ],
            },
        ],
    },
}
