# Generated by Django 3.0.7 on 2020-07-10 20:14

from django.db import migrations, models
import shortener.models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_link_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.SlugField(default=shortener.models.get_slug),
        ),
        migrations.AlterField(
            model_name='link',
            name='target',
            field=models.URLField(max_length=1200, verbose_name='target'),
        ),
    ]
