# Generated by Django 5.2.17 on 2026-09-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0007_link_views"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="domain",
            options={"ordering": ("domain_name",)},
        ),
        migrations.AlterModelOptions(
            name="link",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterField(
            model_name="domain",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="target",
            field=models.CharField(max_length=1200, verbose_name="target"),
        ),
    ]
