# Generated by Django 5.2.17 on 2026-09-28 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("shortener", "0008_alter_domain_options_alter_link_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="desktop_target",
            field=models.CharField(
                blank=True,
                help_text="Optional. Used instead of the target when the link is opened on a desktop computer.",
                max_length=4000,
                verbose_name="desktop target",
            ),
        ),
        migrations.AddField(
            model_name="link",
            name="share_platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("telegram", "Telegram"),
                    ("x", "X / Twitter"),
                    ("bluesky", "Bluesky"),
                    ("threads", "Threads"),
                    ("facebook", "Facebook"),
                    ("linkedin", "LinkedIn"),
                    ("email", "E-mail"),
                    ("sms", "SMS"),
                ],
                max_length=20,
                verbose_name="platform",
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="target",
            field=models.CharField(max_length=4000, verbose_name="target"),
        ),
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="text")),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Optional link to share along with the text. Facebook and LinkedIn can only share a link.",
                        max_length=800,
                        verbose_name="URL",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shortener.domain",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="link",
            name="share",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="shortener.share",
            ),
        ),
    ]
